include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    sort_pub_dependencies: false
    depend_on_referenced_packages: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
