name: news_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  get_it: ^7.7.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.5
  go_router: ^14.0.2
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  collection: ^1.18.0
  equatable: ^2.0.5
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0
  custom_lint: ^0.6.4
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
